server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ /index.html;
    }
}
